test_that("invalid power.en.test input",{
  expect_error(UpdateTargetPower(power.en.test = c(2,2,NA,3)), "Please input valid power.en.test object.")
})

test_that("design call specified sample size",{
  expect_error(UpdateTargetPower(DesignParallelUnequal(diff = -4, sigma1 = 15, sigma2 = 18, deltaL = -19.2,
                                                             deltaU = 19.2, alpha = 0.05, n1 = 10, n2 = 10, seed = 1, sobol = 0),
                                       targetPower = 0.7, plot = FALSE),
               "Please input a power.en.test object generated by specifying targetPower with a valid design type.")
})

test_that("working example design parallel unequal",{
  expect_equal(round(UpdateTargetPower(DesignParallelUnequal(diff = -4, sigma1 = 15, sigma2 = 18, deltaL = -19.2,
                                                             deltaU = 19.2, alpha = 0.05, targetPower = 0.8, q = 1, seed = 1, sobol = 0),
                                       targetPower = 0.7, plot = FALSE)$power,4), 0.7334)
})

test_that("working example design parallel equal",{
  expect_equal(round(UpdateTargetPower(DesignParallelEqual(diff = -4, sigma = 15, deltaL = -19.2,
                                                             deltaU = 19.2, alpha = 0.05, targetPower = 0.8, q = 1, seed = 1, sobol = 0),
                                       targetPower = 0.9, plot = FALSE)$power,4), 0.9092)
})

test_that("working example design one sample",{
  expect_equal(round(UpdateTargetPower(DesignOneSample(mu = -4, sigma = 15, deltaL = -19.2,
                                                          alpha = 0.05, targetPower = 0.8, seed = 1, sobol = 0),
                                       targetPower = 0.75, plot = FALSE)$power,4), 0.7637)
})

test_that("working example design paired sample",{
  expect_equal(round(UpdateTargetPower(DesignPairedSample(diff = -4, sigma1 = 15, sigma2 = 18, rho = 0.25, deltaL = -19.2,
                                                          deltaU = 19.2, targetPower = 0.8, alpha = 0.05, plot = FALSE, seed = 1, sobol = 0),
                                       targetPower = 0.6, plot = FALSE)$power,4), 0.6611)
})

test_that("working example design 2x2 crossover unequal",{
  expect_equal(round(UpdateTargetPower(DesignCrossover2x2Unequal(diff = 0.05, sigma1 = 0.4, sigma2 = 0.3, deltaL = -0.223,
                                                             deltaU = 0.223, alpha = 0.05, targetPower = 0.8, q = 1, seed = 1, sobol = 0),
                                       targetPower = 0.7, plot = FALSE)$power,4), 0.7178)
})

test_that("working example design 2x2 crossover equal",{
  expect_equal(round(UpdateTargetPower(DesignCrossover2x2Equal(diff = 0.05, sigma = 0.4,
                                                                 deltaU = 0.223, alpha = 0.05, targetPower = 0.8, q = 1, seed = 1, sobol = 0),
                                       targetPower = 0.9, plot = FALSE)$power,4), 0.9053)
})

test_that("working example design dual crossover unequal",{
  expect_equal(round(UpdateTargetPower(DesignCrossoverDualUnequal(diff = 0.05, sigma1 = sqrt(3)*0.25, sigma2 = sqrt(3)*0.2, deltaL = -0.223,
                                                                 deltaU = 0.223, alpha = 0.05, targetPower = 0.8, q = 1, seed = 1, sobol = 0),
                                       targetPower = 0.7, plot = FALSE)$power,4), 0.7412)
})

test_that("working example design dual crossover equal noCompSymm",{
  expect_equal(round(UpdateTargetPower(DesignCrossoverDualEqual(diff = 0.05, sigma = sqrt(3)*0.25, deltaL = -0.223, compSymm = FALSE,
                                                                  deltaU = 0.223, alpha = 0.05, targetPower = 0.8, q = 1, seed = 1, sobol = 0),
                                       targetPower = 0.9, plot = FALSE)$power,4), 0.9131)
})

test_that("working example design dual crossover equal CompSymm",{
  expect_equal(round(UpdateTargetPower(DesignCrossoverDualEqual(diff = 0.05, sigma = sqrt(3)*0.25, compSymm = TRUE,
                                                                deltaU = 0.223, alpha = 0.05, targetPower = 0.8, q = 1, seed = 1, sobol = 0),
                                       targetPower = 0.95, plot = FALSE)$power,4), 0.9570)
})
